version: '3.8'

services:
  # Backend development with hot reload
  backend:
    image: python:3.12-slim
    container_name: tf-visualizer-backend-dev
    working_dir: /app
    command: >
      sh -c "pip install -r requirements.txt &&
             python -m flask run --host=0.0.0.0 --port=5000 --reload"
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=backend.api:app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app/backend
      - ./requirements.txt:/app/requirements.txt
      # Mount actual project directories for visualization
      - ../../terraform:/app/project/terraform:ro
      - ../../helm:/app/project/helm:ro
      # Optional: mount test files for demo
      - ./test-terraform:/app/test-terraform
    networks:
      - tf-network

  # Frontend development with webpack dev server
  frontend:
    image: node:18-alpine
    container_name: tf-visualizer-frontend-dev
    working_dir: /app
    command: >
      sh -c "npm install &&
             npm start"
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - tf-network

networks:
  tf-network:
    driver: bridge
