version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tf-visualizer
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount actual project directories for visualization
      - ../../terraform:/app/project/terraform:ro
      - ../../helm:/app/project/helm:ro
      # Optional: mount test files for demo
      - ./test-terraform:/app/test-terraform:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - tf-network

  # Optional: Add a reverse proxy for production-like testing
  nginx:
    image: nginx:alpine
    container_name: tf-visualizer-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - tf-network
    profiles:
      - with-nginx

networks:
  tf-network:
    driver: bridge
