# Terraform S3 backend configuration
# Auto-generated by init-backend.sh for account 803442506948
terraform {
  backend "s3" {
    bucket         = "nova-infra-803442506948-us-east-1-tfstate"
    key            = "terraform.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "nova-infra-terraform-lock"
  }
}
